### ISSUE TITLE
FEATURE REQ: Readable objects

### ISSUE THREAD

**Issue by YuvalAziza** [Ghostopheles/Datamine#13]
Hello, I would to suggest adding a feature to the current datamine_data.lua.  My suggestion is rather simple to say but I don't know how much of hard it is to code it. The suggestion is to add to the datamine the content of the readable items /object one click on. :)

Thanks.

**Comment by Ghostopheles** [comment]
I'll do this - probably for all readable objects as you suggested, plus I still need to cache GossipText I think from NPC dialogues
