### ISSUE TITLE
FEATURE REQ: Patch added.

### ISSUE THREAD

**Issue by YuvalAziza** [Ghostopheles/Datamine#14]
Hello dear Ghost. I dont know How hard it is or if it is possible but It would be nice if on the mouse over tooltip info, there would be a line for Added in Patch: X.y.z

Thanks :)

**Comment by YuvalAziza** [comment]
Shall i remove this req?

**Comment by Ghostopheles** [comment]
Yeah I don't think this is something feasible for me to implement right now - might revisit in the future
