### ISSUE TITLE
FEATURE: Allow users to populate the explorer search w/ a modified click on an item link

### ISSUE THREAD

**Issue by Ghostopheles** [Ghostopheles/Datamine#21]
Similar to auction addons, would be cool to be able to alt-click or shift-click or whatever on an item and search for it in the UI automatically if the UI is shown.

**Comment by lantisnt** [comment]
https://github.com/CoreLootManager/CoreLootManager/blob/master/ClassicLootManager/Modules/Common/Hooks/Hooks.lua

for refference on item link click hooking
